# The credentials.yml.enc file is not kept in our Git repo. There are certain
# constants required for this application. Please edit your copy to include
# the settings below.
#
#   EDITOR=vim rails credentials:edit
#
# Then add to the bottom:
secret_key_base: x

# Use a 32-bit key. Run this in a Rails console to get one:
#   `rake secret`[0..31]
#    => "651c47533d0e85516346c26ade74ab40"
attribute_key: x

font_awesome_download_key: x

aws:
  access_key_id: 123
  secret_access_key: 345
  region: X
  bucket: X

hcaptcha:
  site_key: X
  secret_key: X

vault:
  application: X
  address: X
  token: X
