# The credentials.yml.enc file is not kept in our Git repo. There are certain
# constants required for this application. Please edit your copy to include
# the settings below.
#
#   EDITOR=vim rails credentials:edit
#
# Then add to the bottom:

font_awesome_download_key: 036626216b

aws:
  access_key_id: 123
  secret_access_key: 345
  region: X
  bucket: X

hcaptcha:
  site_key: X
  secret_key: X

vault:
  application: X
  address: X
  token: X
