# The credentials.yml.enc file is not kept in our Git repo. There are certain
# constants required for this application. Please edit your copy to include
# the settings below.
#
#   EDITOR=vim rails credentials:edit
#
# Then add to the bottom:

font_awesome_download_key: 036626216b
vault:
  application: fma_development
  address:
  token: 's.3vlYmKWv2qWr1gzi8guQzexC'
