# The credentials.yml.enc file is not kept in our Git repo. There are certain
# constants required for this application. Please edit your copy to include
# the settings below.
#
# EDITOR=vim rails credentials:edit
#
# Then add to the bottom:

vault:
  application: fma_development
  address:
  token: 's.3vlYmKWv2qWr1gzi8guQzexC'
hcaptcha:
  site_key: '41f3de09-2d15-4d4e-a031-d216f042b92c'
  secret_key: '0x6613592B8ebc54019DdC0A17Ff68d9574705d81d'
